### ISSUE TITLE
[vite-plugin] vuetify:styles fallback timeout hit

### ISSUE THREAD

**Issue by TechAkayy** [vuetifyjs/vuetify-loader#263]
Reopening issue https://github.com/vuetifyjs/vuetify-loader/issues/249 as the issue is still unresolved - styles fallback timeout hit issue. Installed vite-plugin-vuetify to latest. 

Reproduction link: https://stackblitz.com/github/TechAkayy/styles-expose?file=src%2Fmain.js 

![image](https://user-images.githubusercontent.com/73772701/180985656-6a4dd599-9165-4a49-8331-1c2264c8f8b9.png)

Thanks in advance.

**Comment by matkg** [comment]
I had the same issue but it worked as soon as I used these specific package versions inside the package.json

```
"dependencies": {
...
    "vuetify": "3.0.0-beta.6"
}
"devDependencies": {
...
    "@vitejs/plugin-vue": "3.0.1",
    "vite": "3.0.4",
    "vite-plugin-vuetify": "1.0.0-alpha.14"
}
```

**Comment by charrierjc** [comment]
@matkg I still have the issue with the same packages versions as you.
I dont really understand the issue, the build works fine locally in a WSL2, but not at all in the CI, in a docker with node alpine,

**Comment by emikoshi** [comment]
@charrierjc having the same issue as you when updating vite, viteje/plugin-vue and vite-plugin-vuetify.

```
"dependencies": {
...
    "vuetify": "3.0.0-beta.7"
}
"devDependencies": {
...
    "@vitejs/plugin-vue": "3.0.1",
    "vite": "3.0.5",
    "vite-plugin-vuetify": "1.0.0-alpha.14"
}
```

Exposing styles seems to be the culprit, current workaround I found is `plugins: [vue(), vuetify()]` instead of `plugins: [vue(), vuetify({ styles: "expose" })]` in your vite config.

**Comment by KaelWD** [comment]
The stackblitz link crashes with
```
Error [ERR_INTERNAL_ASSERTION]: Error [ERR_INTERNAL_ASSERTION]: TypeError: Cannot destructure property '0' of 'Ue(...)' as it is undefined.
    at formatIterator (https://jvmimllqa--github.w.staticblitz.com/blitz.1f021b18268b32e6c6b2095e039ac8c9f88b0d52.js:6:108233)
    at https://jvmimllqa--github.w.staticblitz.com/blitz.1f021b18268b32e6c6b2095e039ac8c9f88b0d52.js:6:102712
    at formatValue (https://jvmimllqa--github.w.staticblitz.com/blitz.1f021b18268b32e6c6b2095e039ac8c9f88b0d52.js:6:103550)
    at formatProperty (https://jvmimllqa--github.w.staticblitz.com/blitz.1f021b18268b32e6c6b2095e039ac8c9f88b0d52.js:6:108782)
    at https://jvmimllqa--github.w.staticblitz.com/blitz.1f021b18268b32e6c6b2095e039ac8c9f88b0d52.js:6:102747
    at formatValue (https://jvmimllqa--github.w.staticblitz.com/blitz.1f021b18268b32e6c6b2095e039ac8c9f88b0d52.js:6:103550)
    at inspect (https://jvmimllqa--github.w.staticblitz.com/blitz.1f021b18268b32e6c6b2095e039ac8c9f88b0d52.js:6:92243)
    at formatWithOptionsInternal (https://jvmimllqa--github.w.staticblitz.com/blitz.1f021b18268b32e6c6b2095e039ac8c9f88b0d52.js:6:115079)
    at formatWithOptions (https://jvmimllqa--github.w.staticblitz.com/blitz.1f021b18268b32e6c6b2095e039ac8c9f88b0d52.js:6:116334)
    at console.value (https://jvmimllqa--github.w.staticblitz.com/blitz.1f021b18268b32e6c6b2095e039ac8c9f88b0d52.js:6:1056319)
```

but then works fine if I run `npm run dev` again.

**Comment by TechAkayy** [comment]
Thanks @KaelWD for checking at your end. Stackblitz crash doesn't help! 

I was on node v16.14.0 when I created the above reproduction. Here is the github repo of the same - https://github.com/TechAkayy/styles-expose, I have pushed my package-lock file as well into it. 

**Update**: I just updated my node to v16.16.0, and tried again, and I don't see the styles fallback timeout hit anymore. Can others who are having this issue try updating your node to the latest and see if you are still having this issue. 

That said, now, I'm experiencing the other issue when I update my sass file (This variable was not declared with !default in the @used module) which is tracked here - https://github.com/vuetifyjs/vuetify-loader/issues/245, https://github.com/vuetifyjs/vuetify-loader/issues/221

**Comment by funkyvisions** [comment]
I'm still experiencing this with webpack-plugin-vuetify: 2.0.0-alpha.12.  Mostly on our CI machine.  This causes our build to be corrupt, as it appears certain Vuetify components aren't available when this occurs.  If
```
pendingModules: [
    '/Users/mobiledev/build/wcmobile/src/styles/variables.scss',
    '/Users/mobiledev/build/wcmobile/src/styles/variables.scss'
]
```
is output, then I know it worked successfully.  But if there are other pendingModules, then the build is corrupt.  I'm adding a check into my CI build to fail when this happens.

**Comment by KaelWD** [comment]
The new `configFile` option will no longer have this problem, I highly recommend switching. Documentation is updated too: https://next.vuetifyjs.com/en/features/sass-variables/
